from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime


def generate_pdf_report(case_id, case_name, investigator, files, anomalies):
    filename = f"reports/Case_{case_id}_Report.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # ---------- TITLE ----------
    story.append(Paragraph("DIGITAL FORENSICS INVESTIGATION REPORT", styles["Title"]))
    story.append(Spacer(1, 10))

    # ---------- CASE DETAILS ----------
    story.append(Paragraph(f"<b>Case ID:</b> {case_id}", styles["Normal"]))
    story.append(Paragraph(f"<b>Case Name:</b> {case_name}", styles["Normal"]))
    story.append(Paragraph(f"<b>Investigator:</b> {investigator}", styles["Normal"]))
    story.append(Paragraph(f"<b>Generated On:</b> {datetime.now()}", styles["Normal"]))
    story.append(Spacer(1, 10))

    # ---------- SUMMARY ----------
    story.append(Paragraph("1. Investigation Summary", styles["Heading2"]))
    story.append(Paragraph(f"Total Files Scanned: {len(files)}", styles["Normal"]))
    story.append(Paragraph(f"Anomalies Detected: {len(anomalies)}", styles["Normal"]))
    story.append(Spacer(1, 10))

    # ---------- FILE ACTIVITY ----------
    story.append(Paragraph("2. File Activity Summary", styles["Heading2"]))
    story.append(Spacer(1, 5))

    for f in files:
        story.append(Paragraph(
            f"{f['file_path']}<br/>"
            f"Created: {f['created']} | Modified: {f['modified']}",
            styles["Normal"]
        ))
        story.append(Spacer(1, 4))

    # ---------- ANOMALIES ----------
    story.append(Spacer(1, 10))
    story.append(Paragraph("3. Detected Anomalies", styles["Heading2"]))

    if anomalies:
        for a in anomalies:
            story.append(Paragraph(
                f"<b>{a['severity']}</b> - {a['file']}<br/>{a['reason']}",
                styles["Normal"]
            ))
            story.append(Spacer(1, 5))
    else:
        story.append(Paragraph("No suspicious activity detected.", styles["Normal"]))

    # ---------- DISCLAIMER ----------
    story.append(Spacer(1, 10))
    story.append(Paragraph("4. Disclaimer", styles["Heading2"]))
    story.append(Paragraph(
        "This report is generated by an automated forensic analysis tool. "
        "All findings are based on heuristic analysis and require manual verification. "
        "This tool does not determine criminal intent or legality.",
        styles["Normal"]
    ))

    doc.build(story)
    return filename
